[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "joule"
version = "0.9.30"
authors = [
  { name="John Donnal", email="donnal@usna.edu" },
]
description = "Decentralized data processing for IoT platforms"
readme = "README.rst"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: Open Source (see LICENSE)",
    "Operating System :: Linux",
]

[project.urls]
"Homepage" = "https://wattsworth.net/joule/"
"Bug Tracker" = "https://github.com/wattsworth/joule/issues"