#From https://www.infracloud.io/blogs/multi-arch-containers-ci-cd-integration/
name: docker-multi-arch-push
on:
  workflow_run:
    workflows: ["Publish Python Package"]
    types:
      - completed

jobs:
  docker-build-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve commit tag from Workflow A
        id: get_commit_tag
        run:
          echo "Commit Tag: ${{ needs.workflow_a.outputs.commit_tag }}"
      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Login to docker.io container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Test workflow
        run: |
          echo "Here is the ref_name name: ${{ needs.workflow_a.outputs.commit_tag }}"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: wattsworth/joule:latest

      - name: Push Git Tag Image
        run: |
          docker tag wattsworth/joule:latest wattsworth/joule:${{ needs.workflow_a.outputs.commit_tag }}
          docker push wattsworth/joule:${{  needs.workflow_a.outputs.commit_tag }}


