name: Publish Python Package

on:
  push:
    tags:
      - '*'

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Test workflow
        run: |
          echo "Here is the ref_name name: ${{ github.ref_name }}"
          echo "Here is another value: ${{ github.event.workflow_run.head_ref }}"

      - name: Set tag as an output variable
        id: tag_output
        run: echo "tag_name=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"


  docker-build-push:
    needs: build-n-publish
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Login to docker.io container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Test workflow
        run: |
          echo "Here is the ref_name name: ${{  github.ref_name }}"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: wattsworth/joule:latest

      - name: Push Git Tag Image
        run: |
          docker tag wattsworth/joule:latest wattsworth/joule:${{  github.ref_name }}
          docker push wattsworth/joule:${{  github.ref_name }}


